### ISSUE TITLE
Start / Stop / Reset as Insert or PgUp causes fatal error

### ISSUE THREAD

**Issue by etfriedman** [NinjaSnail1080/mc-universal-in-game-timer#6]
When assigning either keybind to Insert or PgUp, I get a fatal error. When I change other keys (i.e. "[" and "\") it works fine. Windows 10.

**Comment by BurAndBY** [comment]
Still a thing
```
Traceback (most recent call last):
  File "pynput\keyboard\__init__.py", line 170, in parse
  File "enum.py", line 387, in __getitem__
KeyError: 'ins'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 549, in <module>
  File "main.py", line 390, in __init__
  File "pynput\keyboard\__init__.py", line 226, in __init__
  File "pynput\keyboard\__init__.py", line 227, in <listcomp>
  File "pynput\keyboard\__init__.py", line 178, in parse
  File "pynput\keyboard\__init__.py", line 179, in <setcomp>
  File "pynput\keyboard\__init__.py", line 172, in parse
ValueError: <Ins>
```
